# Generated by Django 3.1.5 on 2021-01-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsModel',
            new_name='News',
        ),
    ]
