# Generated by Django 3.1.5 on 2021-01-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210125_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-create_time']},
        ),
    ]
