# Generated by Django 3.1.5 on 2021-01-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210125_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sid',
            field=models.IntegerField(db_index=True, default=101),
        ),
    ]
