# Generated by Django 3.1.5 on 2021-01-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NowWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dt', models.BigIntegerField()),
                ('timezone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('main', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=5)),
                ('now_weather', models.ManyToManyField(to='weather.NowWeather')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('now_weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.nowweather')),
            ],
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lot', models.FloatField()),
                ('now_weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.nowweather')),
            ],
        ),
    ]
