# Generated by Django 3.1.5 on 2021-01-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coord',
            old_name='lot',
            new_name='lon',
        ),
    ]
