# Generated by Django 3.1.5 on 2021-01-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210127_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nowweather',
            options={'ordering': ['name', 'dt']},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='now_weather',
        ),
        migrations.AddField(
            model_name='nowweather',
            name='weather',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='weathers', to='weather.weather'),
            preserve_default=False,
        ),
    ]
