# Generated by Django 3.1.5 on 2021-01-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210127_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowweather',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weathers', to='weather.weather'),
        ),
    ]
