# Generated by Django 3.1.5 on 2021-01-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210127_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nowweather',
            name='weather',
        ),
        migrations.AddField(
            model_name='nowweather',
            name='weather_list',
            field=models.ManyToManyField(related_name='now_weather_list', to='weather.Weather'),
        ),
    ]
