# Generated by Django 3.1.5 on 2021-01-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210128_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowweather',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
