# Generated by Django 3.1.5 on 2021-01-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210128_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_day', models.CharField(max_length=8)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone_offset', models.IntegerField()),
            ],
            options={
                'unique_together': {('update_day', 'lat', 'lon')},
            },
        ),
        migrations.CreateModel(
            name='PredictDayWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.BigIntegerField()),
                ('predict_weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='weather.predictweather')),
                ('weather_list', models.ManyToManyField(related_name='predict_day_weather_list', to='weather.Weather')),
            ],
            options={
                'ordering': ['dt'],
            },
        ),
    ]
